#! /bin/sh

if [ $(xrandr --query | grep ' connected' | wc -l) -gt 1 ]
then
    # xrandr --output DVI-D-0 --primary --mode 1920x1080 --rotate normal \
    #        --output DVI-I-0 --mode 1440x900 --rotate normal --above DVI-D-0
    # bspc monitor DVI-D-0 -d 1 2 3 4 5
    # bspc monitor DVI-I-0 -d 6 7 8 9 0
    # bspc monitor --focus DVI-D-0
    # bspc monitor --swap DVI-I-0
    xrandr --output HDMI3 --primary --mode 1920x1080 --rotate normal \
           --output HDMI1 --mode 1440x900 --rotate normal --above HDMI3
    bspc monitor HDMI3 -d 1 2 3 4 5
    bspc monitor HDMI1 -d 6 7 8 9 0
    bspc monitor --focus HDMI1
    bspc monitor --swap HDMI3
    else
        bspc monitor -d 1 2 3 4 5 6 7 8 9 0
fi

sxhkd &
setxkbmap -option "caps:ctrl_modifier,compose:ralt"
setxkbmap -model pc105 -layout us,ru -variant ,phonetic -option grp:ctrls_toggle
xmodmap -e "clear lock"
xinput --set-prop `xinput --list | grep -i mouse | sed -rn 's/^.+id=([0-9]+).+$/\1/p'` 'libinput Accel Speed' -0.8


bspc config border_width         3
bspc config top_padding         35
bspc config window_gap          20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a scratchpad sticky=on state=floating hidden=on
bspc rule -a Gimp state=floating follow=on
bspc rule -a Brave desktop='1'
bspc rule -a Telegram desktop='9'
bspc rule -a Discord desktop='0'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

~/.fehbg &
~/.config/polybar/launch.sh &
# picom &
[ "$(ps -x | grep -c 'scratchpad')" -eq "1" ] && st -c scratchpad &
sleep 5; ~/bin/scratch &

# needed because java is trash
wmname LG3D

# polkit agent
lxsession &

# scratchpad terminal
